@startuml L4_Class Diagram - Model
'https://plantuml.com/class-diagram



class C_API_Model <<C API>> {
    .. Instance Management ..
    GSMP_API Model_Create(Model* instance)
    GSMP_API Model_Destroy(Model* instance)

    .. Runtime ..
    GSMP_API Model_Initialize(Model* instance)
    GSMP_API Model_Reinitialize(Model* instance)
    GSMP_API Model_Step(Model* instance)
    GSMP_API Model_Terminate(Model* instance)

    .. Variables ..
    GSMP_API Model_GetVariableType(Model* instance, char* name, int* type)
    GSMP_API Model_GetVariableDescription(Model* instance, char* name, char* description)
    GSMP_API Model_GetVariableSize(Model* instance, char* name, int* size, int* sizeLength)
    GSMP_API Model_GetVariableIntent(Model* instance, char* name, int* intent)
    GSMP_API Model_SetVariable_Int(Model* instance, char* name, int* value)
    ..  . . .  ..
    GSMP_API Model_GetVariable_Int(Model* instance, char* name, int* value)
    ..  . . .  ..
    GSMP_API Model_GetVariableDefault_Int(Model* instance, char* name, int* defaultValue)
    ..  . . .  ..
}

note right of C_API_Model
    **GSMP_API** is pre-processor
    definition of linkage,
    visibility, & return type.
end note

namespace GSMP {
    abstract Model <<namespace::GSMP>> {
        .. Instantiation ..
        + ReturnCode GetVariableInformation(string information)

        .. Runtime ..
        + {abstract} ReturnCode Initialize()
        + {abstract} ReturnCode Reinitialize()
        + {abstract} ReturnCode Step()
        + {abstract} ReturnCode Terminate()

        .. Variables ..
        + ReturnCode GetVariableType(string name, VariableType type)
        + ReturnCode GetVariableDescription(string name, string description)
        + ReturnCode GetVariableSize(string name, list<int> size)
        + ReturnCode GetVariableIntent(string name, VariableIntent intent)
        + ReturnCode GetVariableDefault(string name, ...???...)
        + ReturnCode GetVariable(string name, ...???...)
        + ReturnCode SetVariable(string name, ...???...)
    }

    note right of Model::GetVariableInformation
        What default format of Interface 
        Requirements Specification for
        the Modelling Platform?
    end note

    class ModelCpp <<namespace::GSMP>> {
        - VariableManager VariableManager

        .. Runtime ..
        + ReturnCode Initialize()
        + ReturnCode Reinitialize()
        + ReturnCode Step()
        + ReturnCode Terminate()

        .. Variables ..
        *Calls VariableManager with Instance*
        ..  . . .  ..
    }

    note right of ModelCpp
        Constructor: Create VariableManager Instance.  
        Create all variables, generating structure of
        all pointers to variables.
    end note

    class ModelC <<namespace::GSMP>> {
        .. Description ..
        * Cpp Implementation of Model to call C_API of ModelCBackend.
        -- TODO --
    }

    note right of ModelC
        Constructor: Create VariableManager Instance.  
        Create all variables, generating structure of
        all pointers to variables.
    end note
}

class ModelCBackend <<C API>> {
    .. Description ..
    * Implementaion of 'Runtime', and uses 'VariableManager' with instance.
    * Defines all C_API functions called by ModelC.
    -- TODO --
}

class C_API_VariableManager <<C API>> {
    Refer to L4_ClassDiagram-VariableManager
}

' -- Relationships --
' Define Cpp relationships
Model --|> ModelCpp : implements

' Define C_API Relationships (including Cpp components)
C_API_Model ..> Model : calls instance
Model --|> ModelC : implements
ModelC .down.> ModelCBackend : wraps
ModelCBackend --> C_API_VariableManager : calls instance

' -- Enumerated Type Definitions --
enum ReturnCode {
    ERROR = -1
    OK = 0
    PENDING = 1
}

enum VariableIntent {
    Undefined
    Input
    Output
    Override
}

enum VariableType {
    double [double]
    single [float]
    byte [int8_t]
    unsignedByte [uint8_t]
    short [int16_t]
    unsignedShort [uint16_t]
    int [int32_t]
    unsignedInt [uint32_t]
    long [int64_t]
    unsignedLong [uint64_t]
    boolean [bool]
    string [char*]
}

' Arrangement
ReturnCode -[hidden]d-> VariableIntent
VariableIntent -[hidden]d-> VariableType

@enduml