@startuml L1_System Context Diagram - Simulation Model Platform

!theme C4_united from <C4/themes>
!include <C4/C4_Context>

Person(User,"User", "An Engineer Simulating Models.")
System(SimulationModelPlatform, "Simulation Model Platform", "Manages **Simulations** of **Model Collections** based on a **User** defined **Simulation Scripts**.","","","","Software System")
System(Models, "Model Architecture Compliant Models", "**Models** built in various different **Model Backends**.")
'System(Example1,"Results Server")
'System(Example2,"Model Database")
'System(Example3,"Scenario Database")

Rel(User, SimulationModelPlatform, "Uses")
Rel(SimulationModelPlatform, Models, "Runs")

@enduml