@startuml L1_System Context Diagram - Simulation Model Platform

!theme C4_united from <C4/themes>
!include <C4/C4_Context>

Person(User,"User", "An Engineer simulating **Scenarios** on a collection of **Models**")
System(GenericSimulationModelPlatform, "Generic Simulation\nModel Platform", "Manages **Simulations** of **Model Collections** based on a **User** defined **Scripts**.","","","","Software System")
System(Models, "Models", "**Models** implementing a consistent **Model Interface** built in various different **Target Backends** (C++, C, etc.).", "", "", "", "Model Architecture Compliant")

Rel(User, GenericSimulationModelPlatform, "Uses")
Rel(GenericSimulationModelPlatform, Models, "Runs")

@enduml