FROM mcr.microsoft.com/devcontainers/cpp:1-ubuntu-24.04

# Install additional packages
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends dotnet-sdk-8.0

# Ensure workspace is allowed by git
RUN git config --global --add safe.directory /workspaces/GSMP